#!/usr/bin/env node
// okf-index.mjs — deterministically (re)build the OKF bundle index for Aeon's
// native knowledge store, memory/topics/index.md (OKF §6, progressive disclosure).
//
// Aeon's OKF setup is intentionally PASSIVE: this regenerator is NOT scheduled and
// NOT gated in CI. Run it on demand (or wire it into memory-flush later) to refresh
// the listing. The MCP server (apps/mcp-server) also synthesizes an index at read
// time per §6, so a stored index.md is a convenience snapshot, not load-bearing.
//
// The generated file:
//   - opens with the bundle-root frontmatter (only place §11 permits it in an
//     index.md): `okf_version: "0.1"` — preserved across regenerations.
//   - lists every concept grouped by `type:`, alphabetically, with its description.
//   - carries NO timestamp, so repeated runs are byte-identical (idempotent).
//
// Usage:
//   node scripts/okf-index.mjs [root]           # write <root>/index.md (default memory/topics)
//   node scripts/okf-index.mjs [root] --check   # exit 1 if <root>/index.md is stale/missing

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, relative, basename } from 'node:path'
import { RESERVED, walk, parseFrontmatter } from './lib/okf.mjs'

const OKF_VERSION = '0.1'

const rawArgs = process.argv.slice(2)
const check = rawArgs.includes('--check')
const root = rawArgs.find(a => !a.startsWith('--')) ?? 'memory/topics'
const indexPath = join(root, 'index.md')

// Collect concepts (non-reserved .md) with their type/title/description + a link
// relative to the bundle root (renders correctly when browsing index.md on GitHub).
const concepts = []
for (const file of walk(root)) {
  if (RESERVED.has(basename(file))) continue
  const fields = parseFrontmatter(readFileSync(file, 'utf-8'))?.fields ?? {}
  const rel = relative(root, file).split('\\').join('/')
  concepts.push({
    type: fields.type || 'Untyped',
    title: fields.title || basename(file, '.md'),
    description: fields.description || '',
    link: rel,
  })
}

// Group by type, sort types and entries deterministically.
const byType = new Map()
for (const c of concepts) {
  if (!byType.has(c.type)) byType.set(c.type, [])
  byType.get(c.type).push(c)
}

let body = `---\nokf_version: "${OKF_VERSION}"\n---\n\n# Knowledge — Aeon OKF bundle\n\n`
body += `Native OKF v${OKF_VERSION} concept store (\`memory/topics/\`). One concept = one markdown file with a \`type:\`. Auto-generated by \`scripts/okf-index.mjs\` — regenerate after adding concepts.\n`

if (concepts.length === 0) {
  body += `\n_No concepts yet._\n`
} else {
  for (const type of [...byType.keys()].sort()) {
    body += `\n# ${type}\n\n`
    const entries = byType.get(type).sort((a, b) => a.title.localeCompare(b.title) || a.link.localeCompare(b.link))
    for (const c of entries) {
      body += c.description ? `* [${c.title}](${c.link}) - ${c.description}\n` : `* [${c.title}](${c.link})\n`
    }
  }
}

if (check) {
  const current = existsSync(indexPath) ? readFileSync(indexPath, 'utf-8') : ''
  if (current !== body) {
    console.error(`okf-index: STALE — ${indexPath} does not match a fresh regen. Run: node scripts/okf-index.mjs ${root}`)
    process.exit(1)
  }
  console.log(`okf-index: OK — ${indexPath} is up to date (${concepts.length} concept(s))`)
} else {
  writeFileSync(indexPath, body)
  console.log(`okf-index: wrote ${indexPath} — ${concepts.length} concept(s) across ${byType.size} type(s)`)
}
